sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t anis016/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anis016/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-582073784658"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY